# Generated by Django 4.1.7 on 2023-04-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="food_capacity",
            new_name="food_capacity_needed",
        ),
        migrations.RenameField(
            model_name="order", old_name="phone", new_name="phone_number",
        ),
    ]
