# Generated by Django 4.1.7 on 2023-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_rename_food_capacity_order_food_capacity_needed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="food_preference",
            field=models.CharField(
                choices=[("V", "Veg"), ("N", "Non Veg"), ("B", "Both")], max_length=1
            ),
        ),
    ]
