# Generated by Django 4.1.7 on 2023-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_restaurant_food_remains_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="food_remains_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="fresh_food_available",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
    ]
