# Generated by Django 4.1.7 on 2023-05-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_restaurant_food_remains_available_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="food_remains_available",
            new_name="food_remains",
        ),
        migrations.RemoveField(model_name="restaurant", name="fresh_food_available",),
        migrations.AddField(
            model_name="restaurant",
            name="fresh_food",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="food_type",
            field=models.CharField(
                choices=[("Veg", "Veg"), ("Non Veg", "Non Veg"), ("Both", "Both")],
                default="Veg",
                max_length=10,
            ),
        ),
    ]
