# Generated by Django 4.1.7 on 2023-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0007_rename_food_remains_available_restaurant_food_remains_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="food_preference",),
        migrations.AddField(
            model_name="order",
            name="food_type",
            field=models.CharField(
                choices=[("Veg", "Veg"), ("Non Veg", "Non Veg"), ("Both", "Both")],
                default="Veg",
                max_length=10,
            ),
        ),
    ]
